/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface:    'var(--color-surface)',
        'surface-2':'var(--color-surface-2)',
        border:     'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        default:    'var(--color-text)',
        muted:      'var(--color-text-muted)',
        faint:      'var(--color-text-faint)',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          'primary':          '#2563EB',
          'primary-content':  '#ffffff',
          'secondary':        '#6366F1',
          'secondary-content':'#ffffff',
          'accent':           '#10B981',
          'accent-content':   '#ffffff',
          'neutral':          '#334155',
          'neutral-content':  '#ffffff',
          'base-100':         '#ffffff',
          'base-200':         '#f1f5f9',
          'base-300':         '#cbd5e1',
          'base-content':     '#0f172a',
          'info':             '#0ea5e9',
          'info-content':     '#ffffff',
          'success':          '#16a34a',
          'success-content':  '#ffffff',
          'warning':          '#d97706',
          'warning-content':  '#ffffff',
          'error':            '#dc2626',
          'error-content':    '#ffffff',
        },
      },
      {
        dark: {
          'primary':          '#3b82f6',
          'primary-content':  '#ffffff',
          'secondary':        '#818cf8',
          'secondary-content':'#ffffff',
          'accent':           '#34d399',
          'accent-content':   '#022c22',
          'neutral':          '#e2e8f0',
          'neutral-content':  '#0f172a',
          'base-100':         '#1e293b',
          'base-200':         '#0f172a',
          'base-300':         '#334155',
          'base-content':     '#f1f5f9',
          'info':             '#38bdf8',
          'info-content':     '#082f49',
          'success':          '#4ade80',
          'success-content':  '#052e16',
          'warning':          '#fbbf24',
          'warning-content':  '#431407',
          'error':            '#f87171',
          'error-content':    '#450a0a',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
  },
};
